stages:
  - prepare
  - lint
  - build
  - deploy

variables:
  LC_ALL: "en_US.UTF-8"

cache:
  key: "bundle_dependencies"
  paths:
  - vendor
  - Pods

.setup: &setup
  - export
  - rvm --create use ruby-2.6.3@restler
  - gem install bundler:2.1.4
  - bundle config set deployment 'true'
  - bundle install

.setup_example_app: &setup_example_app
  - export
  - rvm --create use ${RUBY_VERSION}@${CI_PROJECT_NAME}
  - gem install bundler:2.1.4
  - bundle config set deployment 'true'
  - bundle install
  - cd Restler-Example
  - bundle exec pod install || bundle exec pod install --repo-update
  - envsubst < Restler-Example/Configuration/env_debug.xcconfig.tpl > Restler-Example/Configuration/Debug.xcconfig

prepare_project:
  stage: prepare
  script:
    *setup
  tags:
    - ios

test_project:
  stage: build
  before_script:
    *setup
  script:
    - swift package generate-xcodeproj
    - bundle exec slather setup
    - xcodebuild test -scheme Restler-Package -enableCodeCoverage YES -derivedDataPath "output/derivedData" | bundle exec xcpretty
    - bundle exec slather coverage --verbose
  tags:
    - ios
  dependencies:
    - prepare_project
  coverage: '/Test\ Coverage:\ \D*([\d\.]*)\%/'

build_example_app:
  stage: build
  before_script:
    *setup_example_app
  script:
    - xcodebuild clean | bundle exec xcpretty
    - xcodebuild build -scheme Restler-Example -workspace Restler-Example.xcworkspace | bundle exec xcpretty
  tags:
    - ios
  dependencies:
    - prepare_project

lint_project:
  stage: lint
  before_script:
    *setup
  script:
    - bundle exec fastlane lint_package
  dependencies:
    - prepare_project
  artifacts:
    name: "SwiftLint_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}"
    expire_in: 1 week
    when: always
    paths:
      - output/swiftlint.html
  tags:
    - ios

lint_podspec:
  stage: lint
  before_script:
    *setup
  script:
    - bundle exec pod lib lint --no-clean --skip-tests
  dependencies:
    - prepare_project
  tags:
    - ios

deploy_pod:
  stage: deploy
  before_script:
    *setup
  script:
    - bundle exec fastlane set_podspec_version
    - bundle exec pod trunk push Restler.podspec
  dependencies:
    - test_project
    - build_example_app
    - lint_podspec
    - lint_project
  only:
    - /[\d\.]*/
  except:
    - branches
  tags:
    - ios
