stages:
  - prepare
  - build
  - deploy

variables:
  LC_ALL: "en_US.UTF-8"

.setup: &setup
  - export
  - rvm --create use ruby-2.6.3@restler
  - gem install bundler:2.1.4
  - bundle config set path 'vendor/bundle'
  - bundle install

prepare_project:
  stage: prepare
  script:
    *setup
  tags:
    - ios

test_project:
  stage: build
  before_script:
    *setup
  script:
    - swift package generate-xcodeproj
    - xcodebuild test -scheme Restler-Package -enableCodeCoverage YES
    - bundle exec xcov --scheme Restler-Package --output_directory "output/codecov/xcov/"
  tags:
    - ios
  dependencies:
    - prepare_project
  coverage: '/Restler\.framework\D*\|\D*([\d\.]*)\%/'

lint_podspec:
  stage: build
  before_script:
    *setup
  script:
    - bundle exec pod lib lint --private --no-clean --skip-tests
  dependencies:
    - prepare_project
  tags:
    - ios

deploy_pod:
  stage: deploy
  before_script:
    *setup
  script:
    - bundle exec pod repo push railwaymen-open-rwm_podspec 'Restler.podspec'
  dependencies:
    - test_project
    - lint_podspec
  only:
    - /[\d\.]*/
  except:
    - branches
  tags:
    - ios
